<?php

/**
 * @file
 * Adds the Barrel Roll feature to search forms.
 */

/**
 * Implements hook_config_info().
 */
function doabarrelroll_config_info() {
  $prefixes['doabarrelroll.settings'] = array(
    'label' => t('Do a barrel roll settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_form_alter().
 */
function doabarrelroll_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, array('search_form', 'search_block_form'))) {
    $form['#attached']['js'][] = backdrop_get_path('module', 'doabarrelroll') . '/doabarrelroll.js';
    $form['#attached']['js'][] = array(
      'data' => array('doabarrelroll' => config_get('doabarrelroll.settings', 'doabarrelroll_style')),
      'type' => 'setting',
    );
  }
}

/**
 * Implements hook_menu().
().
 */
function doabarrelroll_menu() {
  $items = array();
  $items['admin/config/user-interface/doabarrelroll'] = array(
    'title' => 'Do a Barrel Roll',
    'description' => 'Configure the Barrel Roll styles.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('doabarrelroll_settings'),
    'access arguments' => array('configure barrel roll'),
  );
  return $items;
}

/**
 * Implements hook_permission().
().
 */
function doabarrelroll_permission() {
  return array(
    'configure barrel roll' => array(
      'title' => t('Configure the barrel roll options'),
    ),
  );
}

/**
 * General configuration form for controlling the barrel roll style.
 */
function doabarrelroll_settings() {
  $form['#config'] = 'doabarrelroll.settings';
  $form['doabarrelroll_style'] = array(
    '#type' => 'checkbox',
    '#title' => t('Do the official barrel roll'),
    '#description' => t('The Barrel Roll, as made famous by Star Fox and Google, is actually a move known by airplane pilots as the Aileron Roll. The actual Barrel Roll is a different move, also supported by this module. After enabling this setting, try typing "Do a Barrel Roll" and "Do an Aileron Roll".' ),
    '#default_value' => config_get('doabarrelroll.settings', 'doabarrelroll_style'),
  );

  return system_settings_form($form);
}
