<?php
/**
 * @file
 * Bootstrap 4 grid plugin for views.
 */

/**
 * Implements hook_autoload_info.
 */
function views_b_grid_autoload_info() {
  return array(
    'views_plugin_style_views_b_grid' => 'views_plugin_style_views_b_grid.inc',
  );
}

/**
 * Implements hook_views_api()
 */
function views_b_grid_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'views_b_grid'),
    'template_path' => backdrop_get_path('module', 'views_b_grid'),
  );
}

/**
 * Preprocess function for views_view_views_b_grid.tpl.php.
 */
function template_preprocess_views_view_views_b_grid(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);
  // Get view options
  $view = $vars['view'];
  $options = $vars['options'];
}
