<?php

/**
* @file
* Removes some links from teasers.
*
*/

/**
 * Implements hook_config_info().
 */
function fixteaserlinks_config_info() {
  $prefixes['fixteaserlinks.settings'] = array(
    'label' => t('Fix Teaser Links settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_node_view_alter().
 */
function fixteaserlinks_node_view_alter(&$build) {
  if ($build['#view_mode'] == 'teaser') {
    if (config_get('fixteaserlinks.settings', 'comment')) {
      // remove "add comment" link from node teaser mode display
      unset($build['links']['comment']['#links']['comment-add']);
      // and if logged out this will cause another list item to appear, so let's get rid of that
      unset($build['links']['comment']['#links']['comment-forbidden']);
    }
    // Get rid of "read more" as well.
    if (config_get('fixteaserlinks.settings', 'readmore')) {
      unset($build['links']['node']['#links']['node-readmore']);
    }
  }
}
