<?php
/**
 * @file
 * Install, update and uninstall functions for the css_editor module.
 */

/**
 * Migrate css_editor variables to config.
 *
 * Useful for Drupal 7 to Backdrop CMS upgrades.
 */
function css_editor_update_1000() {
  $config = config('css_editor.settings');
  $config->set('css_editor_enabled_themes', update_variable_get('css_editor_enabled_themes', array()));
  $config->save();

  update_variable_del('css_editor_enabled_themes');
}
